### ISSUE TITLE
Pandoc Applescript Error

### ISSUE THREAD

**Issue by mugsuk** [Jmuccigr/AppleScripts#1]
Hi John

Thank you very much for sharing your AppleScript - I would love to use it but have run up against an error despite copying your code directly into AppleScript. The error message is...

Script Error: Expected “then”, etc. but found unknown token.

		if fname ­ "" and not validFile then
           ↑
line 104, column 11 in Pandoc.applescript

I was wondering if you have run up against this, and if so, how you solved it.

Thanks Again.

Murray

**Comment by Jmuccigr** [comment]
I don't have a script by that name. Did you mean `Process document.applescript`?

If so, I run it all the time without this error. Did you perhaps copy the file (and not clone/download it) and lose the "not equal to" sign `≠` in that line?

**Comment by mugsuk** [comment]
Hi John (thanks for the reply).

Yes it is the “Process document.applescript”.

I cloned the code, but nowhere is there a "not equal too” sign around line 104. I have attached a screen shot below of the code as it appears on Github. Am I doing something stupid like using the wrong encoding in my browser (pretty sure it is unicode UTF-8)?

Cheers

Murray

**Comment by Jmuccigr** [comment]
I don't see a screen shot, but yes there should be a ≠ after `fname`. You could also use `<>`.

Hmmm, GitHub doesn't seem to like that character. I'll look into it.

**Comment by mugsuk** [comment]
Hi John

Thanks again for your time.

I have attached the AppleScript based on the raw code on Github - I’ think their may be more than one character issue?

Could you please mail a copy of your working script and I can see then if that works.

Cheers.

Murray

**Comment by Jmuccigr** [comment]
Again, nothing attached that I can see, but I've removed those pesky characters from the script and updated it on GitHub. It seems like the Script Editor saves text files in the Western charset instead of unicode. It'll read the file if I convert it to unicode, but will save it back to Western the next time.

This also means that other scripts have the same issues, I think.

**Comment by mugsuk** [comment]
Excellent - thanks John

The script ran perfectly after I changed some of my PATHS and output settings.

Yours sincerely

Murray
